# Generated by Django 2.2.11 on 2020-03-30 07:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_donation_donor_recipient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='transaction_date_and_time',
        ),
        migrations.AddField(
            model_name='donation',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 30, 7, 7, 26, 166277, tzinfo=utc)),
        ),
    ]
