# Generated by Django 2.2.11 on 2020-03-30 10:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200330_1541'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TwilioSMSDevice',
            new_name='SMSDevice',
        ),
        migrations.AlterField(
            model_name='donation',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 30, 10, 35, 10, 126205, tzinfo=utc)),
        ),
    ]
