# Generated by Django 2.2.11 on 2020-03-30 10:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200330_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 30, 10, 47, 10, 704785, tzinfo=utc)),
        ),
    ]
