# Generated by Django 2.2.11 on 2020-03-30 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200330_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
