# Generated by Django 2.2.11 on 2020-03-30 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200330_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='mobile',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='smsdevice',
            name='number',
            field=models.CharField(help_text='The mobile number to deliver tokens to (E.164).', max_length=15),
        ),
    ]
